### ISSUE TITLE
Error running pangolin with vcf files

### ISSUE THREAD

**Issue by PedroBarbosa** [tkzeng/Pangolin#5]
Hi,

I'm setting up pangolin in our cluster, and I am struggling to make it work for the VCF example file (csv works fine).

```
pangolin examples/brca.vcf GRCh37.primary_assembly.genome.fa gencode.v38lift37.annotation.db brca

Using CPU
Traceback (most recent call last):
  File "/home/pedro.barbosa/software/miniconda3/envs/pangolin/bin/pangolin", line 8, in <module>
    sys.exit(main())
  File "/home/pedro.barbosa/software/miniconda3/envs/pangolin/lib/python3.6/site-packages/pangolin/pangolin.py", line 240, in main
    "Format: gene|pos:score_change|pos:score_change|...",'.','.')
TypeError: __new__() missing 1 required positional argument: 'type_code'
```

Was there any update in the pyvcf dependency that was not accounted for ? I didn't specify version for the dependencies, just followed the github instructions. Please find below the versions I'm using:

pangolin (1.0.2)
pyvcf (0.6.8)
pyfaidx (0.7.0)
gffutils (0.11.0)
biopython (1.79)

Best, 
Pedro

**Comment by PedroBarbosa** [comment]
Solved by installing pyvcf via mamba/conda.

**Comment by sruthisrini** [comment]
Hey @PedroBarbosa ,

I am getting a similar error like yours. But, I didn't understand the solution that you have used. Could you help me out. 

These are the versions for packages I used:
pangolin (1.0.2)
pyvcf (0.6.8)
pyfaidx (0.8.1.1)
gffutils (0.12)
biopython (1.83)

I used this command with vcf as input file:
`pangolin /Pangolin/examples/cosmic_pangolin.vcf /gencode.v43.pc_transcripts.fa /Pangolin/gencode.v38.annotation.db cosmic_pangolin`

The error I got:

```
Using CPU
Traceback (most recent call last):
  File "/Users/sruthisrinivasan/miniconda3/bin/pangolin", line 8, in <module>
    sys.exit(main())
  File "/Users/sruthisrinivasan/miniconda3/lib/python3.10/site-packages/pangolin/pangolin.py", line 244, in main
    variants.infos["Pangolin"] = vcf.parser._Info(
TypeError: Info.__new__() missing 1 required positional argument: 'type_code'
```

Please help in solving this issue.

Thanks,
Sruthi
